version: '3.1'

services:

  redis:
    image: 'redis'
    container_name: 'redis'
    restart: 'always'
    ports:
      - '6379:6379'

  node:
    image: 'node-balanced'
    restart: 'always'
    ports:
      - '8080:8080'
    links:
      - 'redis'

  nginx:
    image: nginx-balancer
    container_name: 'nginx'
    ports:
      - "80:80"
    links:
      - node
