version: '3.1'

services:

  postgres:
    image: 'postgres:alpine'
    container_name: 'pedronobrega-postgres'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker

  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'pedronobrega-rabbit'
    restart: 'always'
    ports:
      - '15672:15672'
      - '5672:5672'

  server:
    image: 'node-server'
    container_name: 'pedronobrega-server'
    restart: 'always'
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
      - 'rabbit'
    links:
      - 'postgres'
      - 'rabbit'

  worker:
    image: 'node-worker'
    container_name: 'pedronobrega-worker'
    restart: 'always'
    ports:
      - '8081:8081'
    depends_on:
      - 'postgres'
      - 'rabbit'
    links:
      - 'postgres'
      - 'rabbit'

  # nginx:
  #   image: 'nginx-balancer'
  #   container_name: 'pedronobrega-nginx'
  #   ports:
  #     - '80:80'
  #   links:
  #     - 'node'
